In [27]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
gene_ranks_df = pd.read_csv('rankingSystem.csv')
gene_ranks_df

,nodeID,log_bc_ratio,Module Appearance Score,Cluster Y/N,Average Shortest Path Length
0,AARSD1,-0.263763,0,0,4.113746
1,ABCA1,NaN,0,0,4.391077
2,ABCA2,NaN,0,0,4.445338
3,ABCE1,NaN,0,0,4.391077
4,ABI1,NaN,0,0,4.445338
5,ABI3BP,NaN,0,0,4.027331
6,ABL1,NaN,0,0,3.813103
7,ACAA2,NaN,0,0,4.096061
8,ACACA,NaN,0,0,3.992363
9,ACAT1,NaN,0,0,4.238746
10,ACOT7,NaN,0,0,3.992363
11,ACP2,NaN,0,0,5.088826
12,ACSF2,-0.303361,21,0,3.743569
13,ACSF3,NaN,0,0,3.813103
14,ACSS1,NaN,0,0,3.813103
15,ACTA1,NaN,0,1,3.956994
16,ACTA2,NaN,0,0,3.956994
17,ACTB,NaN,0,1,3.956994
18,ACTC1,NaN,0,0,4.257637
19,ACTN1,0.023092,48,0,3.573151
20,ACTN2,-0.400161,0,0,3.754019
21,ACTN4,-0.198481,38,0,4.214228
22,ACTR2,NaN,0,0,3.956994
23,ACY1,NaN,0,0,5.018891
24,ADA,NaN,0,0,3.936093
25,ADAM33,NaN,0,0,4.468248
26,ADAMTSL4,NaN,0,0,4.289791
27,ADAR,0.243000,208,0,3.283762
28,ADCY6,NaN,0,0,3.992363
29,ADD3,NaN,0,0,3.992363
...,...,...,...,...,...
2467,ZHX1,NaN,31,0,3.992363
2468,ZHX2,NaN,0,0,3.992363
2469,ZHX3,NaN,0,0,3.992363
2470,ZIC1,NaN,0,0,4.257637
2471,ZMAT2,NaN,0,0,3.979904
2472,ZNF136,NaN,0,0,4.288987
2473,ZNF233,NaN,0,0,4.445338
2474,ZNF263,NaN,0,0,4.356511
2475,ZNF276,NaN,0,0,3.992363
2476,ZNF318,NaN,0,0,5.018891
2477,ZNF391,NaN,0,0,4.447749
2478,ZNF451,NaN,0,0,3.979904
2479,ZNF488,NaN,0,0,3.992363
2480,ZNF576,NaN,0,0,5.090032
2481,ZNF598,NaN,0,0,4.502412
2482,ZNF609,NaN,0,0,3.992363
2483,ZNF638,NaN,0,0,4.121785
2484,ZNF639,NaN,0,0,4.195338
2485,ZNF655,NaN,0,0,3.979904
2486,ZNF746,NaN,0,0,4.238746
2487,ZNF804A,NaN,0,0,3.992363
2488,ZNHIT2,NaN,0,0,4.606913
2489,ZNRD1,-0.106350,9,0,3.910772
2490,ZNRF4,NaN,0,0,4.495579
2491,ZRANB1,NaN,0,0,4.321543
2492,ZSCAN1,NaN,0,0,3.992363
2493,ZSWIM8,NaN,0,0,3.992363
2494,ZW10,NaN,0,0,4.502412
2495,ZXDC,NaN,0,0,3.992363
2496,ZYX,NaN,0,0,3.992363

In [32]:
gene_ranks_df['overall_score'] = (
    (gene_ranks_df['log_bc_ratio'] / max(gene_ranks_df['log_bc_ratio']) * 100) +
    (gene_ranks_df['Module Appearance Score'] / max(gene_ranks_df['Module Appearance Score']) * 100) +
    (gene_ranks_df['Cluster Y/N'] / max(gene_ranks_df['Cluster Y/N']) * 100) +
    (gene_ranks_df['Average Shortest Path Length'] / max(gene_ranks_df['Average Shortest Path Length']) * 100)
)

In [37]:
ranked_genes = gene_ranks_df.sort_values('overall_score', ascending=False)
ranked_genes.to_csv('ranked_genes.csv')